services:
    database:
        image: ghcr.io/alex4270/geocoding-microservice-database:latest
    backend:
        image: ghcr.io/alex4270/geocoding-microservice:latest
        environment:
            DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=18&charset=utf8"
        restart: unless-stopped
        depends_on:
            - database
        networks:
            - geocoding-microservice-network
            - traefik_proxy
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.geocoding-microservice.rule=Host(`${APP_URL}`)"
            - "traefik.http.routers.geocoding-microservice.entrypoints=websecure"
            - "traefik.http.routers.geocoding-microservice.tls=true"
            - "traefik.http.routers.geocoding-microservice.tls.certResolver=le"
            - "traefik.http.services.geocoding-microservice.loadbalancer.server.port=80"

# Internal
networks:
    traefik_proxy:
         external: true